### ISSUE TITLE
Spinning loader when trying to click through a Broker's Client info (Console)

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#158]
Example (logged in as Admin):

Broker Management > Candy Bednar > Clients Tab > Sundance Vacations = spinning loader

**Comment by patricksheedy** [comment]
The problem is that Candy Bednar's account has a null ApplicationReference. Dennis fixed these in QA, the same thing needs to be done in prod.

**Comment by patricksheedy** [comment]
USE [RSICodeGenerators]
GO

SELECT *
  FROM [dbo].[Clients]
  where ContactFirstName = 'candy'
GO

**Comment by patricksheedy** [comment]
Dennis will update the references.

**Comment by hutch77** [comment]
This needs to be updated asap, @patricksheedy is it something you can do since @DennisRSI is buried?

**Comment by patricksheedy** [comment]
Fixed in the production database. It should work now.

**Comment by hutch77** [comment]
@patricksheedy - this is still an issue on the Broker Ron White. I've tried with other brokers and it seems to work fine but specifically not Ron White. Unfortunately, this is the Broker Todd wants to walk through the site tomorrow.
